### ISSUE TITLE
mobius.py full is including date in 2020-04-05 set

### ISSUE THREAD

**Issue by jwhendy** [datasciencecampus/mobility-report-data-extractor#29]
**Describe the bug**
In the csvs created using `python ./mobius.py full -d date_file pdf_path svg_path output`, if one uses the `2020-04-05` date file, you end up with the date in the country and region columns.

**To Reproduce**
```
$ git log
commit e71ff2615927142dd8b753ce7caecd7777d9b443
```

I have [a file](https://github.com/jwhendy/covid19/blob/master/lib/mobility-code-list.txt) of all `US-*` codes, `mobility-code-list.txt`

I run this:
```
#!/bin/bash

PATH=/home/jwhendy/vault/personal/covid19
cd $PATH/mobility-report-data-extractor
Y='2020'
M='04'
D='05'
date=${Y}-${M}-${D}

while read code; do
  /usr/bin/python ./mobius.py download $code $date
  /dates_lookup_2020_04_05.csv
  /usr/bin/python ./mobius.py full -d ./config/dates_lookup_${Y}_${M}_${D} pdfs/${code}_${date}.pdf svgs/${code}_${date}.svg ./output
done < $PATH/lib/mobility-code-list.txt
```

The output from `2020-03-29` is fine, but this is the output with `2020-04-05`:

![grab_2020-04-12_130555](https://user-images.githubusercontent.com/379357/79076266-5fbbe000-7cbe-11ea-9b24-a56485b6e477.png)

**Expected behavior**
The date string should be stripped from the country/region names.

**Comment by jwhendy** [comment]
Probably not helpful for an real fix, but this is my downstream workaround:
```
df_mod['country'] = df_mod['country'].str.split(' April 5, 2020', expand=True)[0]
df_mod['region'] = df_mod['region'].str.split(' April 5, 2020', expand=True)[0]
```
```

**Comment by mshodge** [comment]
Hey @jwhendy good spot. The date was hard coded in the original. I have updated the code now so it should work with the two date lookup files and also future ones (as longs as they adhere to the `dates_lookup_YYYY_MM_DD.csv` convention.

**Comment by jwhendy** [comment]
Hmmm. Did something else change?

```
$ git log
commit 4b59d99db5f7574e433915f402308de89a303eda

$ /usr/bin/python ./mobius.py full -d ./config/dates_lookup_2020_04_05.csv pdfs/US-Alabama_2020-04-05.pdf svgs/US-Alabama_2020-04-05.svg ./output
Traceback (most recent call last):
  File "./mobius.py", line 245, in <module>
    cli()
  File "/home/jwhendy/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jwhendy/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jwhendy/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jwhendy/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jwhendy/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./mobius.py", line 227, in full
    summary_df = mobius.extraction.summarise(doc, dates_file)
  File "/mnt/vault/personal/covid19/mobility-report-data-extractor/mobius/extraction.py", line 325, in summarise
    date_object = datetime.strptime(date_string, '%Y_%m_%d')
  File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y_%m_%d'
```

```
$ git checkout HEAD^1
$ git log
commit e71ff2615927142dd8b753ce7caecd7777d9b443

$ /usr/bin/python ./mobius.py full -d ./config/dates_lookup_2020_04_05.csv pdfs/US-Alabama_2020-04-05.pdf svgs/US-Alabama_2020-04-05.svg ./output
Extracting plot summaries: 1it [00:00,  2.75it/s
...
```

**Comment by mshodge** [comment]
Hmm no. It seems to work for me. What OS are you on?

**Comment by mshodge** [comment]
Ah I see. It's because I call `config/dates_file.csv` whereas you call `./config/dates_files` and the code splits the string at `.`. I will fix now so it doesn't matter which you use.

**Comment by mshodge** [comment]
Ok @jwhendy  just pushed a change, it splits at `.csv` instead now which makes it more robust.
